name: this_is_a_to_do_app

description: "CS4750 Final Project"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  table_calendar: ^3.2.0
  syncfusion_flutter_calendar: ^29.1.37
  provider: ^6.1.4
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  image_path: "lib/assets/icons2/512.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
